// packages/vue/src/LiteTreeNodes.vue
<template>
  <ul  data-lite-tree :class="['lite-tree-nodes']">
    <li  data-lite-tree v-for="(node, index) in nodes" :key="index">
      <span  data-lite-tree class="lite-tree-node" 
        @click="toggleNode(node)"
        :class="node.classs" 
        :style="node.style">
        <span  data-lite-tree class="flag" v-if="treeCtx.hasFlag">
          <RichLabel :value="node.flag" />
        </span>
        <span  data-lite-tree class="indent" :style="{ width: indent + 'px' }"></span>
        <span 
          data-lite-tree
          v-if="hasChildren(node)"
          :class="[
            'opener',
            'icon',
            'arrow',
            { open: isNodeOpen(node) }]"/>
        <span data-lite-tree class="icon" :class="node.icon ? node.icon : (hasChildren(node) ? isNodeOpen(node) ? 'folder-open':'folder' : 'file')"/>
        <span  data-lite-tree class="title">
          <RichLabel :value="node.title" />
          <RichLabel class="tag" v-for="tag in node.tags" :key="tag" :value="tag" />
        </span>
        <RichLabel  class="comment" :value="node.comment" />
      </span>
      <SlideUpDown :active="isNodeOpen(node)" :duration="200">
        <LiteTreeNodes v-if="hasChildren(node) && isNodeOpen(node)" :indent="indent + 20"
          :class="isNodeOpen(node) ? 'open' : 'close'" :nodes="node.children">
        </LiteTreeNodes>
      </SlideUpDown>
    </li>
  </ul>
</template>

<script setup lang="ts">
import { withDefaults, inject } from 'vue';
import type { LiteTreeNode,LiteTreeContext ,LiteTreeNodesProps } from '@common/types';
import RichLabel from './RichLabel.vue';
import { LiteTreeContextId } from '@common/consts'; 
// @ts-ignore
import SlideUpDown from 'vue-slide-up-down'

const props = withDefaults(defineProps<LiteTreeNodesProps>(), {
  indent: 0,
  nodes: () => ([])
});

const treeCtx = inject<LiteTreeContext>(LiteTreeContextId)!

// 展开/折叠节点
const toggleNode = (node: LiteTreeNode): void => {
  node.open = node.open == undefined ? false : !node.open;
};
// 是否有子节点
const hasChildren = (node: LiteTreeNode): boolean => {
  return Array.isArray(node.children) && node.children.length > 0;
};
// 节点是否已打开
const isNodeOpen = (node: LiteTreeNode): boolean => {
  return node.open == undefined ? true : node.open;
}; 
 

</script>

<script lang="ts">
export default {}
</script>

// packages/react/src/LiteTreeNodes.tsx
import React,{useCallback, useContext, useState }from "react"
import type { LiteTreeNode } from "@common/types"
import {toStyleObject} from "@common/utils/toStyleObject"
import classnames from "classnames"
import RichLabel from "./RichLabel"
import {SlideDown} from 'react-slidedown' 
import { Context } from "./context"

export type LiteTreeNodesProps =React.PropsWithRef<{
    nodes:LiteTreeNode[]
    indent?:number
}>

const LiteTreeNodes:React.FC<LiteTreeNodesProps> =(props) => {
    const {indent=0} = props    
    const [nodes,setNodes] = useState<LiteTreeNode[]>(()=>props.nodes)
    const toggleNode = useCallback((node:LiteTreeNode)=>{ 
        setNodes(nodes.map(n=>n.id===node.id ? {...n,open:!n.open} : n))
    },[nodes])
    const treeCtx = useContext(Context)        
    return  (<ul data-lite-tree className="lite-tree-nodes">
        { nodes.map((node,index)=>{
            const hasChildren = node.children && node.children.length > 0
            return (<li data-lite-tree key={index}>
                <span data-lite-tree className={"lite-tree-node "+node.classs.join(" ")} 
                    onClick={()=>toggleNode(node)}
                    style={toStyleObject(node.style)}>
                    {/* 显示标识 */}
                    { treeCtx.hasFlag ? <span data-lite-tree className ="flag">                        
                        <RichLabel value={node.flag}/>
                    </span> : null } 
                    {/* 缩进距离 */}
                    <span data-lite-tree className="indent" style={ {width: indent + 'em'} }></span>
                    {/* 展开折叠指示符 */}
                    { hasChildren ? <span data-lite-tree className={classnames('opener','icon','arrow',{ open: node.open})} /> : null}
                    {/* 图标 */}
                    <span data-lite-tree className={classnames("icon",node.icon ? node.icon :{
                        'folder-open': hasChildren && node.open,
                        'folder': hasChildren && !node.open,
                        'file': !hasChildren})
                    }/>
                    {/* 标题 */}
                    <span data-lite-tree className="title">
                        <RichLabel value={node.title}/>
                        {/* 标签 */}    
                        { node.tags.map((tag,index)=><RichLabel className="tag" key={index} value={tag}/>) }
                    </span>
                    {/* 注释 */}
                    <RichLabel className="comment" value={node.comment} />
                </span>
                {/* 子节点 */}
                { node.children && node.children.length>0 ?                         (
                        <SlideDown closed={!node.open}>
                            <LiteTreeNodes nodes={node.children} indent={indent+2}/>
                        </SlideDown>
                    ) : null
                }   
            </li>)
        })}
    </ul>)

}

export default LiteTreeNodes
