// packages/vue/src/RichLabel.vue
<template>
    <span  data-lite-tree style="display:inline-flex" :style="styled.style" :class="styled.classs" v-html="parseLinks(styled.value)"> </span>
</template>
<script setup lang="ts">
import { inject } from 'vue';
import type { LiteTreeContext } from '@common/types';
import { LiteTreeContextId } from '@common/consts';
import { StyledString } from '@common/utils/styledString';
import { parseLinks } from '@common/utils/parseLinks';

const props = defineProps({
  value: {
    type: String,
    default: ''
  } 
});
const treeCtx = inject<LiteTreeContext>(LiteTreeContextId)!
const styled = StyledString(props.value,treeCtx.styles);
</script>

// packages/react/src/RichLabel.tsx
import React,{useContext }from "react"
import { Context } from "./context"
import { StyledString } from "@common/utils/styledString"
import { toStyleObject } from "@common/utils/toStyleObject"
import { parseLinks } from '@common/utils/parseLinks';

export  interface RichLabelProps{
    value:string
    className?:string
    style?:React.CSSProperties
}

const RichLabel:React.FC<RichLabelProps> = (props:RichLabelProps) => {
    const { className='', style:inlineStyle={} } = props
    const treeCtx = useContext(Context)
    const {style,classs=[],value} = StyledString(props.value,treeCtx.styles);
    return <span
        data-lite-tree
        className={className + " " +classs.join(" ")}
        style={{display:"inline-flex",...inlineStyle,...toStyleObject(style)!}}
        dangerouslySetInnerHTML={{__html: parseLinks(value)}}    
    />
}


export default RichLabel
